-- ============================================================
-- Central SCI — Inserção dos 90 locais de extintor
-- ============================================================

insert into locais (numero, edificacao, descricao, tem_slot_a, tem_slot_b, planta_tipo_exigido, planta_cap_ext_exigida) values
(1,  'RÁDIO',            'Rádio',                              true, false, 'CO²',    '5-B:C'),
(2,  'RÁDIO',            'Copa',                               true, false, 'CO²',    '5-B:C'),
(3,  'RÁDIO',            'Meteorologia',                       true, false, 'CO²',    '5-B:C'),
(4,  'RÁDIO',            'Elevador cobertura',                 true, false, 'CO²',    '5-B:C'),
(5,  'RÁDIO',            'Elevador térreo',                    true, false, 'CO²',    '5-B:C'),
(6,  'RÁDIO',            'Central de alarme',                  true, false, 'PQS BC', '20-B:C'),
(7,  'RÁDIO',            'Central de alarme',                  true, false, 'CO²',    '5-B:C'),
(8,  'RÁDIO',            'Central de alarme',                  true, false, 'CO²',    '5-B:C'),
(9,  'RÁDIO',            'Andar 5/Equipamentos',               true, false, 'CO²',    '5-B:C'),
(10, 'RÁDIO',            'Máquina do Elevador',                true, false, 'CO²',    '5-B:C'),
(11, 'ADM',              'Corredor auditório',                 true, false, 'CO²',    '5-B:C'),
(12, 'ADM',              'Corredor auditório',                 true, false, 'PQS ABC', '2-A;20-B:C'),
(13, 'ADM',              'Corredor almoxarife',                true, false, 'CO²',    '5-B:C'),
(14, 'ADM',              'Corredor almoxarife',                true, false, 'PQS ABC', '2-A;20-B:C'),
(15, 'CASA DE BOMBAS',   'Casa de Bombas',                     true, false, 'CO²',    '5-B:C'),
(16, 'TPS TÉRREO',       'Porta principal lado embarque',      true, false, 'PQS ABC', '2-A;20-B:C'),
(17, 'TPS TÉRREO',       'Saída Charlie',                      true, false, 'PQS ABC', '2-A;20-B:C'),
(18, 'TPS TÉRREO',       'Central de alarme',                  true, false, 'CO²',    '5-B:C'),
(19, 'TPS TÉRREO',       'Do lado do DEA',                     true, false, 'PQS ABC', '4-A;40-B:C'),
(20, 'TPS TÉRREO',       'Ao lado do banheiro',                true, false, 'PQS ABC', '2-A;20-B:C'),
(21, 'TPS TÉRREO',       'Elevador',                           true, false, 'CO²',    '5-B:C'),
(22, 'TPS TÉRREO',       'Porta principal lado desembarque',   true, false, 'PQS ABC', '2-A;20-B:C'),
(23, 'TPS TÉRREO',       'Saída do desembarque',               true, false, 'CO²',    '5-B:C'),
(24, 'DESEMBARQUE',      'Ao lado da sala técnica',            true, false, 'PQS ABC', '2-A;20-B:C'),
(25, 'DESEMBARQUE',      'Lado esquerdo',                      true, false, 'PQS ABC', '2-A;20-B:C'),
(26, 'DESEMBARQUE',      'Ao lado do hidrante',                true, false, 'PQS ABC', '2-A;20-B:C'),
(27, 'DESEMBARQUE',      'Porta lado ar',                      true, false, 'PQS ABC', '2-A;20-B:C'),
(28, 'TPS SUPERIOR',     'Ao lado do elevador',                true, false, 'PQS ABC', '2-A;20-B:C'),
(29, 'TPS SUPERIOR',     'Início do corredor',                 true, false, 'PQS ABC', '2-A;20-B:C'),
(30, 'TPS SUPERIOR',     'Corredor, frente ao COE',            true, false, 'PQS BC', '20-B:C'),
(31, 'TPS SUPERIOR',     'Ao lado da saída de emergência',     true, false, 'PQS ABC', '2-A;20-B:C'),
(32, 'TPS TÉRREO',       'Sala de máquina elevador',           true, false, 'CO²',    '5-B:C'),
(33, 'TPS TÉRREO',       'Sala telemática',                    true, false, 'CO²',    '5-B:C'),
(34, 'TPS SUPERIOR',     'Sala COE',                           true, false, 'PQS ABC', '2-A;20-B:C'),
(35, 'TPS SUPERIOR',     'Sala COE',                           true, false, 'CO²',    '5-B:C'),
(36, 'TPS SUPERIOR',     'Sala COE (Quadro elétrico)',         true, false, 'PQS ABC', '2-A;20-B:C'),
(37, 'TPS SUPERIOR',     'Sala COE STVV',                      true, false, 'CO²',    '5-B:C'),
(38, 'RAIO X',           'Entrada',                            true, false, 'PQS ABC', '2-A;20-B:C'),
(39, 'RAIO X',           'Quadro de energia',                  true, false, 'CO²',    '5-B:C'),
(40, 'RAIO X',           'Próximo a escada rolante',           true, false, 'PQS ABC', '2-A;20-B:C'),
(41, 'EMBARQUE',         'Próximo a porta 1',                  true, false, 'PQS ABC', '2-A;20-B:C'),
(42, 'EMBARQUE',         'Próximo a porta 2',                  true, false, 'PQS ABC', '2-A;20-B:C'),
(43, 'EMBARQUE',         'Ao lado do elevador',                true, false, 'PQS ABC', '2-A;20-B:C'),
(44, 'EMBARQUE',         'Ao lado do Aéro Coffee',             true, false, 'CO²',    '5-B:C'),
(45, 'EMBARQUE',         'Sala Ar-condicionado',               true, false, 'PQS BC', '20-B:C'),
(46, 'ELOS',             'Corredor direito',                   true, false, 'PQS ABC', '2-A;20-B:C'),
(47, 'ELOS',             'Posição 6 elevador',                 true, false, 'PQS ABC', '2-A;20-B:C'),
(48, 'ELOS',             'Posição 6 corredor',                 true, false, 'PQS BC', '20-B:C'),
(49, 'ELOS',             'Posição 7 corredor',                 true, false, 'PQS ABC', '2-A;20-B:C'),
(50, 'ELOS',             'Posição 7 elevador',                 true, false, 'PQS ABC', '2-A;20-B:C'),
(51, 'ELOS',             'Posição 7 externo',                  true, false, 'PQS BC', '20-B:C'),
(52, 'ELOS',             'Posição 6 externo',                  true, false, 'PQS BC', '20-B:C'),
(53, 'APOC',             'Sala do APOC',                       true, false, 'PQS BC', '20-B:C'),
(54, 'APOC',             'Sala do APOC',                       true, false, 'CO²',    '5-B:C'),
(55, 'APOC',             'Banheiro/Copa',                      true, false, 'PQS BC', '20-B:C'),
(56, 'APOC',             'Ao lado do hidrante',                true, false, 'PQS ABC', '2-A;20-B:C'),
(57, 'PORTÃO 1',         'Guarita',                            true, false, 'PQS ABC', '2-A;20-B:C'),
(58, 'KF CHILLER',       'Ao lado do P1',                      true, false, 'CO²',    '5-B:C'),
(59, 'KF',               'Interna da KF',                      true, false, 'CO²',    '5-B:C'),
(60, 'KF',               'Interna da KF',                      true, false, 'CO²',    '5-B:C'),
(61, 'KF CHILLER',       'Entrada do Chiller',                 true, false, 'PQS BC', '20-B:C'),
(62, 'KF CHILLER',       'Entrada do Chiller',                 true, false, 'CO²',    '5-B:C'),
(63, 'PAA',              'Próximo do PAA',                     true, false, 'PQS ABC', '2-A;20-B:C'),
(64, 'PAA',              'Próximo do PAA',                     true, false, 'PQS ABC', '2-A;20-B:C'),
(65, 'PAA',              'Próximo do PAA',                     true, false, 'PQS BC', '20-B:C'),
(66, 'PAA',              'Próximo do PAA',                     true, false, 'PQS BC', '20-B:C'),
(67, 'MANUTENÇÃO',       'Entrada',                            true, false, 'PQS BC', '20-B:C'),
(68, 'MANUTENÇÃO',       'Entrada',                            true, false, 'PQS BC', '20-B:C'),
(69, 'MANUTENÇÃO',       'Entrada',                            true, false, 'CO²',    '5-B:C'),
(70, 'MANUTENÇÃO',       'Corredor',                           true, false, 'PQS ABC', '2-A;20-B:C'),
(71, 'MANUTENÇÃO',       'Corredor',                           true, false, 'PQS ABC', '2-A;20-B:C'),
(72, 'GSE GOL AZUL RP',  'Corredor',                           true, false, 'PQS ABC', '2-A;20-B:C'),
(73, 'GSE GOL AZUL RP',  'Corredor',                           true, false, 'PQS ABC', '2-A;20-B:C'),
(74, 'GSE GOL AZUL RP',  'Manutenção GOL',                     true, false, 'PQS ABC', '2-A;20-B:C'),
(75, 'GSE GOL AZUL RP',  'Manutenção AZUL',                    true, false, 'PQS ABC', '2-A;20-B:C'),
(76, 'SCI',              'Garagem',                            true, false, 'PQS ABC', '2-A;20-B:C'),
(77, 'SCI',              'Garagem',                            true, false, 'PQS BC', '20-B:C'),
(78, 'SCI',              'Academia',                           true, false, 'CO²',    '5-B:C'),
(79, 'SCI',              'Garagem',                            true, false, 'PQS BC', '20-B:C'),
(80, 'SCI',              'Reserva',                            true, false, 'PQS ABC', '2-A;20-B:C'),
(81, 'SCI',              'Auditório',                          true, false, 'PQS ABC', '2-A;20-B:C'),
(82, 'SCI',              'Auditório',                          true, false, 'PQS BC', '20-B:C'),
(83, 'TPS TÉRREO',       'Sala de apoio/fiscal',               true, false, 'CO²',    '5-B:C'),
(84, 'RÁDIO',            'Sala TEC VHF',                       true, false, 'CO²',    '5-B:C'),
(85, 'TPS TÉRREO',       'Frente ao guichê Localiza',          true, false, 'PQS ABC', '2-A;20-B:C'),
(86, 'SCI',              'Almox SCI',                          true, false, 'PQS ABC', '2-A;20-B:C'),
(87, 'SCI',              'Almox SCI',                          true, false, 'PQS BC', '20-B:C'),
(88, 'CAMPO DE ANTENAS', 'Sala 01 | Chave: 01',               true, false, 'CO²',    '5-B:C'),
(89, 'CAMPO DE ANTENAS', 'Sala 03 | Chave: 03',               true, false, 'CO²',    '5-B:C'),
(97, 'TPS SUPERIOR',     'Caixa d''água',                      true, false, 'PQS BC', '20-B:C');
